Repository nestjs/typeorm, pull requests merged in 2019-02, with the labels that each got.

#56 getRepositoryToken returns correct tokens for custom repositories
  lib/common/typeorm.utils.ts
Labels: bug

#54 feature: options factory for multiple connections
  lib/interfaces/typeorm-options.interface.ts
  lib/typeorm-core.module.ts
Labels: enhancement

#53 refactor(@nestjs/typeorm): logger improvement
  lib/common/typeorm.utils.ts
Labels: enhancement, status: merge

#51 fix(TypeOrmCoreModule): add more Type casting to onModuleDestroy
  lib/common/typeorm.utils.ts
  lib/typeorm-core.module.ts
Labels: refactor, status: merge
